zig build-exe src/main.zig \
  -target wasm32-freestanding \
  --import-memory \
  -fno-entry \
  --export=alloc \
  --export=free \
  --export=grayscale \
  --export=invert \
  --export=brightness \
  --export=threshold \
  --export=sepia \
  -O ReleaseFast \
  -femit-bin=public/image_transformer.wasm
